book_shops/config/routes.rb
BookShops::Application.routes.draw do
  resources :users
  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  resources :book_shops  do
    resources :books
  end

  root "book_shops#index"

end

book_shops/app/models/book.rb
class Book < ActiveRecord::Base
	validates :book_name,:book_description, :book_price, :book_author, :presence=>true
	belongs_to :book_shop
end

book_shops/app/models/book_shop.rb
class BookShop < ActiveRecord::Base
	validates :shop_name,:shop_location,:presence=>true,length: {minimum: 5, maximum:15}
	validates :phone_number, numericality: true, length: {is: 10}, :presence=>true 
	validates :email_address, uniqueness: true, length: {minimum: 7, maximum:25},:presence=>true
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	has_many :books
end

book_shops/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
 
end

book_shops/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

book_shops/app/controllers/book_shops_controller.rb
class BookShopsController < ApplicationController
  
  layout "book_shops"
  #before_filter :require_login, only: [:index,:new,:create,:edit,:update,:destroy]
  def index
    @bookshops = BookShop.all
  end

  def new
    @shop = BookShop.new
  end

  def create
    @shop = BookShop.new(set_database_field)
    binding.pry
    if @shop.save
      flash[:msg] = "Bookshop Store in a database please check your email"
      EmailNotification.delay(run_at: 5.minutes.from_now).notify(@shop)
      render "new"
    else

       render "new"
    end
  end

  def edit
    @shop = BookShop.find(params[:id])
  end

  def update
    @shop = BookShop.find(params[:id])
    if @shop.update(set_database_field)
    end
  end

  def destroy
    @shop = BookShop.find(params[:id])
    if @shop.destroy
      flash[:sucess]="#{@shop.shop_name}  Book Shop Sucessfuly Deleted"
      redirect_to book_shops_path
    end
  end

  private def set_database_field
    params.require(:book_shop).permit(:shop_name, :shop_location, :phone_number, :email_address, :image)
  end
end

book_shops/app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  layout "book_shops"
  #before_filter :require_login, only: [:index,:new,:create,:edit,:update,:destroy] 
  def index 
    @book_shop = find_book_shop_params
    @books = @book_shop.books.all
  end

  def new
    @book_shop = find_book_shop_params
    @book = @book_shop.books.new
  end

  def create
    @book_shop = find_book_shop_params
    @book = @book_shop.books.new(set_db_field)
    if @book.save
      flash[:message] = "books sucessfully saved"
      redirect_to book_shop_books_path(@book_shop) 
    else
      flash[:message] = "Sorry something goes wrong cannot saved"
      redirect_to book_shop_books_path(@book_shop)
    end

  end

  def edit
     @book_shop = find_book_shop_params
     @book = @book_shop.books.find(params[:id])
  end

  def update
    @book_shop = find_book_shop_params
    @book = @book_shop.books.find(params[:id])
    if @book.update(set_db_field) 
    end
  end

  def destroy
    @book_shop = find_book_shop_params
    @book = @book_shop.books.find(params[:id])
    if @book.destroy
      flash[:message]="#{@book.book_name}  Sucessfully Deleted"
      redirect_to book_shop_books_path(@book_shop)
    end
  end

  private 
  def find_book_shop_params
    BookShop.find(params[:book_shop_id])
  end
  def set_db_field
    params.require(:book).permit(:book_name, :book_description, :book_price, :book_author)
  end
end

book_shops/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(book_shops_path, notice: 'Logged out!')
  end
end

book_shops/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout "book_shops"
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
  end


  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

book_shops/app/helpers/application_helper.rb
module ApplicationHelper
end

book_shops/app/helpers/authors_helper.rb
module AuthorsHelper
end

book_shops/app/helpers/book_shops_helper.rb
module BookShopsHelper
end

book_shops/app/helpers/books_helper.rb
module BooksHelper
end

book_shops/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

book_shops/app/helpers/users_helper.rb
module UsersHelper
end

book_shops/app/views/book_shops/_form.html.erb
<div id="container">
	<section>
	<%if @shop.errors.full_messages.any?%>
		<%@shop.errors.full_messages.each do |e|%>
		<div class="error"><%=e%><br></div>
		<%end%>
		<%end%>
		<%if flash[:msg]%>
			<div class="error"><%=flash[:msg]%></div>
		<%end%>
		<%=form_for @shop do |f|%>
		<p>
			<%=f.label "Enter Shop name", :class=>"form_label"%>
			<%=f.text_field :shop_name, :class=>"form_field", :placeholder=>"Eg: ekta Books"%>
		</p>	
		<p>
			<%=f.label "Enter Shop Location" , :class=>"form_label"%>
			<%=f.text_field :shop_location, :class=>"form_field",:placeholder=>"Eg: lalitpur"%>
		</p>
		<p>
			<%=f.label "Enter Shop Phone Number", :class=>"form_label"%>
			<%=f.text_field :phone_number, :class=>"form_field",:placeholder=>"Eg: 999999999"%>
		</p>
		<p>	
			<%=f.label "Enter Shop Email Address", :class=>"form_label"%>
			<%=f.text_field :email_address, :class=>"form_field",:placeholder=>"Eg: ekta@ekta.com"%>
		</p>
		<p>
			<%=f.label "Upload Shop Logo", :class=>"form_label"%>
			<%=f.file_field :image, :class=>"file_field",:placeholder=>"Eg: ekta@ekta.com"%>
		</p>
		<p>
		<%=f.submit("Create New Shop", :class=>"form_submit")%>
		</p>
		<%end%>
	</section>
</div>

book_shops/app/views/book_shops/_header.html.erb
<header id="top_nav">
	<a href="/book_shops" class="logo">
		<h1>Book shop</h1>
		<h2>Online Book</h2>
	</a>
	<nav>
		<ul>
			<li><%=link_to("Home", book_shops_path)%></li>
			<li><%=link_to("View Shop",book_shops_path)%></li>
			<%unless logged_in? %>
			<li><%=link_to("Create New Account", new_user_path)%></li>
			<li><%=link_to("Login",login_path)%></li>
			<%else%>
			<li><%=link_to("Create New Shop", new_book_shop_path)%></li>
			<li><%=link_to("Logout",logout_path)%></li>
			<%end%>
		</ul>
	</nav>
</header>

book_shops/app/views/book_shops/create.html.erb
<h1>BookShops#create</h1>
<p>Find me in app/views/book_shops/create.html.erb</p>

book_shops/app/views/book_shops/delete.html.erb
<h1>BookShops#delete</h1>
<p>Find me in app/views/book_shops/delete.html.erb</p>

book_shops/app/views/book_shops/destroy.html.erb
<h1>BookShops#destroy</h1>
<p>Find me in app/views/book_shops/destroy.html.erb</p>

book_shops/app/views/book_shops/edit.html.erb
<div id="container">
	<section>
	<%if @shop.errors.full_messages.any?%>
		<%@shop.errors.full_messages.each do |e|%>
		<div class="error"><%=e%><br></div>
		<%end%>
		<%end%>
		<%if flash[:msg]%>
			<div class="error"><%=flash[:msg]%></div>
		<%end%>
		<%=form_for @shop do |f|%>
		<p>
			<%=f.label "Enter Shop name", :class=>"form_label"%>
			<%=f.text_field :shop_name, :class=>"form_field", :placeholder=>"Eg: ekta Books"%>
		</p>	
		<p>
			<%=f.label "Enter Shop Location" , :class=>"form_label"%>
			<%=f.text_field :shop_location, :class=>"form_field",:placeholder=>"Eg: lalitpur"%>
		</p>
		<p>
			<%=f.label "Enter Shop Phone Number", :class=>"form_label"%>
			<%=f.text_field :phone_number, :class=>"form_field",:placeholder=>"Eg: 999999999"%>
		</p>
		<p>	
			<%=f.label "Enter Shop Email Address", :class=>"form_label"%>
			<%=f.text_field :email_address, :class=>"form_field",:placeholder=>"Eg: ekta@ekta.com"%>
		</p>
		<p>
			<%=f.label "Upload Shop Logo", :class=>"form_label"%>
			<%=f.file_field :image, :class=>"file_field",:placeholder=>"Eg: ekta@ekta.com"%>
		</p>
		<p>
		<%=f.submit("update shop", :class=>"form_submit")%>
		</p>
		<%end%>
	</section>
</div>

book_shops/app/views/book_shops/index.html.erb
<div id="container">
<%if flash[:sucess]%>
	<h3><%=flash[:sucess]%></h3>
<%end%>	
	<%@bookshops.each do |s|%>
		<div id="index_all">
		<%=image_tag s.image.url, :id=>"shop_img"%>
		<h3><%=s.shop_name%></h3>
		<p><%=s.shop_location%></p>
		<p><%=s.email_address%></p>
		<p>Phone No.  <%=s.phone_number%></p>
		<br><br>
		<% if logged_in?%>
		<%=link_to("Store books",new_book_shop_book_path(s.id))%>
		<%=link_to("View Books",book_shop_books_path(s.id))%>
		<%=link_to("Edit Shop", edit_book_shop_path(s.id))%>
		<%=link_to("Delete Shop", book_shop_path(s.id), method: :delete, data: { confirm: 'Are you sure?' } )%>
		<%else%>
		<%=link_to("View Books",book_shop_books_path(s.id))%>
		<%end%>
	</div>
<%end%>
</div>

book_shops/app/views/book_shops/new.html.erb
<%=render "form"%>

book_shops/app/views/book_shops/show.html.erb
<h1>BookShops#show</h1>
<p>Find me in app/views/book_shops/show.html.erb</p>

book_shops/app/views/book_shops/update.html.erb
<h1>BookShops#update</h1>
<p>Find me in app/views/book_shops/update.html.erb</p>

book_shops/app/views/books/_form.html.erb
<div id="container">
	<section>
		<%=form_for @book, url: book_shop_book_path(@book_shop, @book) do |f|%>
		<p>
			<%=f.label "Enter Book name", :class=>"form_label"%>
			<%=f.text_field :book_name, :class=>"form_field", :placeholder=>"Eg: Ruby On rails"%>
		</p>	
		<p>
			<%=f.label "Enter Book Description" , :class=>"form_label"%>
			<%=f.text_area :book_description, :cols=>30,:rows=>2, :class=>"form_field",:placeholder=>"Eg: Learn Web Development with Rails"%>
		</p>
		<p>
			<%=f.label "Enter Book Price", :class=>"form_label"%>
			<%=f.text_field :book_price, :class=>"form_field",:placeholder=>"Eg: 200"%>
		</p>
		<p>	
			<%=f.label "Enter Book Author", :class=>"form_label"%>
			<%=f.text_field :book_author, :class=>"form_field",:placeholder=>"Eg: Michael Hartl"%>
		</p>
		<p>
		<%=f.submit("Create New Shop", :class=>"form_submit")%>
		</p>
		<%end%>
	</section>
</div>

book_shops/app/views/books/_header.html.erb
<header id="top_nav">
	<a href="/book_shops" class="logo">
		<h1>Book shop</h1>
		<h2>Online Book</h2>
	</a>
	<nav>
		<ul>
			<li><%=link_to("Home", book_shops_path)%></li>
			<li><%=link_to("View Shop",book_shops_path)%></li>
			<%unless logged_in? %>
			<li><%=link_to("Create New Account", new_user_path)%></li>
			<li><%=link_to("Login",login_path)%></li>
			<%else%>
			<li><%=link_to("Create New Shop", new_book_shop_path)%></li>
			<li><%=link_to("Logout",logout_path)%></li>
			<%end%>
		</ul>
	</nav>
</header>

book_shops/app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

book_shops/app/views/books/edit.html.erb
<div id="container">
	<section>
		<%=form_for @book, url: book_shop_book_path(@book_shop, @book) do |f|%>
		<p>
			<%=f.label "Enter Book name", :class=>"form_label"%>
			<%=f.text_field :book_name, :class=>"form_field", :placeholder=>"Eg: Ruby On rails"%>
		</p>	
		<p>
			<%=f.label "Enter Book Description" , :class=>"form_label"%>
			<%=f.text_area :book_description, :cols=>30,:rows=>2, :class=>"form_field",:placeholder=>"Eg: Learn Web Development with Rails"%>
		</p>
		<p>
			<%=f.label "Enter Book Price", :class=>"form_label"%>
			<%=f.text_field :book_price, :class=>"form_field",:placeholder=>"Eg: 200"%>
		</p>
		<p>	
			<%=f.label "Enter Book Author", :class=>"form_label"%>
			<%=f.text_field :book_author, :class=>"form_field",:placeholder=>"Eg: Michael Hartl"%>
		</p>
		<p>
		<%=f.submit("Update Book", :class=>"form_submit")%>
		</p>
		<%end%>
	</section>
</div>

book_shops/app/views/books/index.html.erb
<div id="container">
<%if flash[:message]%>
	<h3><%=flash[:message]%></h3>
<%end%>
<% unless @books.empty? %>
<%@books.each do |s|%>
	<div id="index_all">
	<h3><%=s.book_name%></h3>
	<p><%=s.book_description%></p>
	<p>$<%=s.book_price%></p>
	<p><%=s.book_author%></p>
	<br><br>
	<%if logged_in?%>
<%=link_to("Edit Book",edit_book_shop_book_path(@book_shop,s.id))%>
<%=link_to("Delete Book", book_shop_book_path(@book_shop,s.id),method: :delete, data: { confirm: 'Are you sure?' } )%>
<%end%>
</div>
<%end%>
<%else%>
<h3>Currently There Are no Books Available</h3>

<%end%>
</div>

book_shops/app/views/books/new.html.erb
<div id="container">
	<section>
	<%if @book.errors.full_messages.any?%>
		<%@book.errors.full_messages.each do |e|%>
		<div class="error"><%=e%><br></div>
		<%end%>
		<%end%>
		<%=form_for @book, url:{:action=>"create"} do |f|%>
		<p>
			<%=f.label "Enter Book name", :class=>"form_label"%>
			<%=f.text_field :book_name, :class=>"form_field", :placeholder=>"Eg: Ruby On rails"%>
		</p>	
		<p>
			<%=f.label "Enter Book Description" , :class=>"form_label"%>
			<%=f.text_area :book_description, :cols=>30,:rows=>2, :class=>"form_field",:placeholder=>"Eg: Learn Web Development with Rails"%>
		</p>
		<p>
			<%=f.label "Enter Book Price", :class=>"form_label"%>
			<%=f.text_field :book_price, :class=>"form_field",:placeholder=>"Eg: 200"%>
		</p>
		<p>	
			<%=f.label "Enter Book Author", :class=>"form_label"%>
			<%=f.text_field :book_author, :class=>"form_field",:placeholder=>"Eg: Michael Hartl"%>
		</p>
		<p>
		<%=f.submit("Create New Shop", :class=>"form_submit")%>
		</p>
		<%end%>
	</section>
</div>

book_shops/app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

book_shops/app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

book_shops/app/views/email_notification/notify.html.erb
khjkjgkj

book_shops/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookShops</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>

book_shops/app/views/layouts/book_shops.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookShops</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "header"%>
<%= yield %>
 </body>
</html>

book_shops/app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag user_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>
<div class="linker">
<%= link_to 'Back',book_shops_path%>
</div>

book_shops/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

book_shops/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

book_shops/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_confirmation %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

book_shops/app/views/users/new.html.erb
<div class="link">
<%=link_to "Go Back", book_shops_path %>
</div>
<%=render "form"%>

book_shops/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>